async_spram_4x1:
  source:
    - ram/asyn_spram_4x1/asyn_spram_4x1.v
  top_module: asyn_spram_4x1

dual_port_ram_16k:
  source:
    - ram/dual_port_ram_16k/dual_port_ram_16k.v
  top_module: dual_port_ram_16k

dual_port_ram_1k:
  source:
    - ram/dual_port_ram_1k/dual_port_ram_1k.v
  top_module: dual_port_ram_1k

fifo_dual_port_ram:
  source:
    - ram/fifo/rtl/fifo.v
    - ram/fifo/rtl/sync_dual_port_ram.v
  top_module: fifo

pipelined_8bit_adder:
  source:
    - ram/pipelined_8bit_adder/pipelined_8bit_adder.v
  top_module: pipelined_8bit_adder

syn_spram_4x1:
  source:
    - ram/syn_spram_4x1/syn_spram_4x1.v
  top_module: syn_spram_4x1

dual_port_ram_8x16_mif:
  source:
    - ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif/dual_port_ram_8x16_mif.v
  top_module: dual_port_ram_8x16_mif
  cocotb_dir: ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif

dual_port_ram_8x16_mif_4clk:
  source:
    - ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif_4clk/dual_port_ram_8x16_mif_4clk.v
    - ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif_4clk/dual_port_ram_8x16_mif.v
  top_module: dual_port_ram_8x16_mif_4clk
  cocotb_dir: ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif_4clk

dual_port_ram_8x16_mif_8clk:
  source:
    - ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif_8clk/dual_port_ram_8x16_mif_8clk.v
    - ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif_8clk/dual_port_ram_8x16_mif.v
  top_module: dual_port_ram_8x16_mif_8clk
  cocotb_dir: ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif_8clk

dual_port_ram_8x16_mif_16clk:
  source:
    - ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif_16clk/dual_port_ram_8x16_mif_16clk.v
    - ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif_16clk/dual_port_ram_8x16_mif.v
  top_module: dual_port_ram_8x16_mif_16clk
  cocotb_dir: ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif_16clk

dual_port_ram_8x16_mif_24clk:
  source:
    - ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif_24clk/dual_port_ram_8x16_mif_24clk.v
    - ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif_24clk/dual_port_ram_8x16_mif.v
  top_module: dual_port_ram_8x16_mif_24clk
  cocotb_dir: ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif_24clk

dual_port_ram_8x16_mif_32clk:
  source:
    - ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif_32clk/dual_port_ram_8x16_mif_32clk.v
    - ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif_32clk/dual_port_ram_8x16_mif.v
  top_module: dual_port_ram_8x16_mif_32clk
  cocotb_dir: ram/dual_port_ram_8x16_mif_multi_clk/dual_port_ram_8x16_mif_32clk
