name: Code Format

# Run CI on push, PR, and weekly.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0 " # weekly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Multiple job to tests
jobs:
  change_detect:
    name: "Check"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "Python"
            code_type: "-py"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Checkout infra
        uses: actions/checkout@v4
        with:
          repository: Re-FACT/refact_infra
          path: utils/refact_infra

      - name: Install dependencies
        run: |
          sudo python3 -m pip install -r requirements.txt
          
      - name: Dump tool versions
        run: |
          black --version

      - name: Check format
        run: make check-format${{ matrix.config.code_type }} INFRA_ROOT=utils/refact_infra
